export { default as Landing } from './Landing';
export { default as UserDetails } from './UserDetails';
export { default as GameDetails } from './GameDetails';
export { default as CommentsContainer } from './CommentsContainer';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Logout } from './Logout';
export { default as GameList } from './GameList';
