import React from 'react';
import useLanguage from '@/i18n/hooks';
import {
  Container, Title, Text, Subtitle, Subtitle2, Li, Ul, Strong, Subtitle3,
} from './styles';

const Privacy = () => {
  const { t } = useLanguage();
  return (
    <Container>
      <Title>{t('privacy-policy-1')}</Title>
      <Text>{t('privacy-policy-2')}</Text>
      <Text>
        {t('privacy-policy-3')}
      </Text>
      <Text>
        {t('privacy-policy-4')}
      </Text>
      <Subtitle>{t('privacy-policy-5')}</Subtitle>
      <Subtitle2>{t('privacy-policy-6')}</Subtitle2>
      <Text>
        {t('privacy-policy-7')}
      </Text>
      <Subtitle2>{t('privacy-policy-8')}</Subtitle2>
      <Text>{t('privacy-policy-9')}</Text>
      <Ul>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-10')}</Strong>
            {t('privacy-policy-11')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-12')}</Strong>
            {t('privacy-policy-13')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-14')}</Strong>
            {t('privacy-policy-15')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-16')}</Strong>
            {t('privacy-policy-17')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-18')}</Strong>
            {t('privacy-policy-19')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-20')}</Strong>
            {t('privacy-policy-21')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-22')}</Strong>
            {t('privacy-policy-23')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-24')}</Strong>
            {t('privacy-policy-25')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-26')}</Strong>
            {t('privacy-policy-27')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-28')}</Strong>
            {t('privacy-policy-29')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-30')}</Strong>
            {t('privacy-policy-31')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-32')}</Strong>
            {t('privacy-policy-33')}
          </Text>
        </Li>

        <Li>
          <Text>
            <Strong>{t('privacy-policy-34')}</Strong>
            {t('privacy-policy-35')}
            <a href="https://gametrail.vercel.app" rel="external nofollow noopener noreferrer" target="_blank">https://gametrail.vercel.app</a>
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-36')}</Strong>
            {t('privacy-policy-37')}
          </Text>
        </Li>
      </Ul>
      <Subtitle>{t('privacy-policy-38')}</Subtitle>
      <Subtitle2>{t('privacy-policy-39')}</Subtitle2>
      <Subtitle3>{t('privacy-policy-40')}</Subtitle3>
      <Text>{t('privacy-policy-41')}</Text>
      <Ul>
        <Li>
          <Text>{t('privacy-policy-42')}</Text>
        </Li>
        <Li>
          <Text>{t('privacy-policy-44')}</Text>
        </Li>
      </Ul>
      <Subtitle3>{t('privacy-policy-44')}</Subtitle3>
      <Text>{t('privacy-policy-45')}</Text>
      <Text>{t('privacy-policy-46')}</Text>
      <Text>{t('privacy-policy-47')}</Text>
      <Text>{t('privacy-policy-48')}</Text>
      <Subtitle3>{t('privacy-policy-49')}</Subtitle3>
      <Subtitle3>{t('privacy-policy-50')}</Subtitle3>
      <Text>{t('privacy-policy-51')}</Text>
      <Ul>
        <Li>
          <Strong>{t('privacy-policy-52')}</Strong>
          {t('privacy-policy-53')}
        </Li>
        <Li>
          <Strong>{t('privacy-policy-54')}</Strong>
          {t('privacy-policy-55')}
        </Li>
      </Ul>
      <Text>
        {t('privacy-policy-56')}
        <a href="https://www.privacypolicies.com/blog/privacy-policy-template/#Use_Of_Cookies_Log_Files_And_Tracking" target="_blank" rel="noreferrer">Políticas de privacidad</a>
      </Text>
      <Ul>
        <Li>
          <Text><Strong>{t('privacy-policy-57')}</Strong></Text>
          <Text>{t('privacy-policy-58')}</Text>
          <Text>{t('privacy-policy-59')}</Text>
          <Text>{t('privacy-policy-60')}</Text>
        </Li>
        <Li>
          <Text><Strong>{t('privacy-policy-61')}</Strong></Text>
          <Text>{t('privacy-policy-62')}</Text>
          <Text>{t('privacy-policy-63')}</Text>
          <Text>{t('privacy-policy-64')}</Text>
        </Li>
        <Li>
          <Text><Strong>{t('privacy-policy-65')}</Strong></Text>
          <Text>{t('privacy-policy-66')}</Text>
          <Text>{t('privacy-policy-67')}</Text>
          <Text>{t('privacy-policy-68')}</Text>
        </Li>
      </Ul>
      <Text>{t('privacy-policy-69')}</Text>
      <Subtitle2>{t('privacy-policy-70')}</Subtitle2>
      <Text>{t('privacy-policy-71')}</Text>
      <Ul>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-72')}</Strong>
            {t('privacy-policy-71')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-72')}</Strong>
            {' '}
            {t('privacy-policy-73')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-74')}</Strong>
            {' '}
            {t('privacy-policy-75')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-76')}</Strong>
            {' '}
            {t('privacy-policy-77')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-78')}</Strong>
            {' '}
            {t('privacy-policy-79')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-80')}</Strong>
            {' '}
            {t('privacy-policy-81')}
          </Text>
        </Li>
        <Li>
          <Text>
            <Strong>{t('privacy-policy-82')}</Strong>
            {' '}
            {t('privacy-policy-83')}
          </Text>
        </Li>
      </Ul>
      <Subtitle2>{t('privacy-policy-86')}</Subtitle2>
      <Text>{t('privacy-policy-87')}</Text>
      <Text>{t('privacy-policy-88')}</Text>
      <Subtitle2>{t('privacy-policy-89')}</Subtitle2>
      <Text>{t('privacy-policy-90')}</Text>
      <Text>{t('privacy-policy-91')}</Text>
      <Text>{t('privacy-policy-92')}</Text>
      <Subtitle2>{t('privacy-policy-93')}</Subtitle2>
      <Text>{t('privacy-policy-94')}</Text>
      <Text>{t('privacy-policy-95')}</Text>
      <Text>{t('privacy-policy-96')}</Text>
      <Text>{t('privacy-policy-97')}</Text>
      <Subtitle2>{t('privacy-policy-98')}</Subtitle2>
      <Subtitle3>{t('privacy-policy-99')}</Subtitle3>
      <Text>{t('privacy-policy-100')}</Text>
      <Subtitle3>{t('privacy-policy-101')}</Subtitle3>
      <Text>{t('privacy-policy-102')}</Text>
      <Subtitle3>{t('privacy-policy-103')}</Subtitle3>
      <Text>{t('privacy-policy-104')}</Text>
      <Subtitle3>{t('privacy-policy-105')}</Subtitle3>
      <Text>{t('privacy-policy-106')}</Text>
      <Ul>
        <Li>{t('privacy-policy-107')}</Li>
        <Li>{t('privacy-policy-108')}</Li>
        <Li>{t('privacy-policy-109')}</Li>
        <Li>{t('privacy-policy-110')}</Li>
        <Li>{t('privacy-policy-111')}</Li>
      </Ul>
      <Subtitle2>{t('privacy-policy-112')}</Subtitle2>
      <Text>{t('privacy-policy-113')}</Text>
      <Subtitle>{t('privacy-policy-114')}</Subtitle>
      <Text>{t('privacy-policy-115')}</Text>
      <Text>{t('privacy-policy-116')}</Text>
      <Subtitle>{t('privacy-policy-117')}</Subtitle>
      <Text>{t('privacy-policy-118')}</Text>
      <Text>{t('privacy-policy-119')}</Text>
      <Subtitle>{t('privacy-policy-120')}</Subtitle>
      <Text>{t('privacy-policy-121')}</Text>
      <Subtitle>{t('privacy-policy-122')}</Subtitle>
      <Text>{t('privacy-policy-123')}</Text>
      <Ul>
        <Li>{t('privacy-policy-124')}</Li>
      </Ul>
    </Container>
  );
};

export default Privacy;
